# Generated by Django 4.2.3 on 2023-08-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0002_remove_customermodel_cus_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="ecommerce_app.categorymodel",
            ),
        ),
    ]
