# Generated by Django 4.2.3 on 2023-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0003_productmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="prd_price",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="prd_addate",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
