# Generated by Django 4.2.3 on 2023-08-03 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce_app", "0005_ordermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermodel",
            name="cus_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_model",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
