# Generated by Django 4.2.3 on 2023-08-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0006_alter_customermodel_cus_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartmodel",
            old_name="customer",
            new_name="Cart_customer",
        ),
        migrations.RenameField(
            model_name="cartmodel",
            old_name="product",
            new_name="Cart_product",
        ),
    ]
