# Generated by Django 4.2.3 on 2023-08-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0007_rename_customer_cartmodel_cart_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartmodel",
            name="total_price",
            field=models.FloatField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="cartmodel",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
