# Generated by Django 4.2.3 on 2023-08-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0008_cartmodel_total_price_alter_cartmodel_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartmodel",
            name="Cart_customer",
        ),
        migrations.RemoveField(
            model_name="cartmodel",
            name="Cart_product",
        ),
        migrations.AddField(
            model_name="cartmodel",
            name="customer",
            field=models.ForeignKey(
                max_length=70,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce_app.customermodel",
            ),
        ),
        migrations.AddField(
            model_name="cartmodel",
            name="product",
            field=models.ForeignKey(
                max_length=70,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce_app.productmodel",
            ),
        ),
    ]
