# Generated by Django 4.2.3 on 2023-08-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0009_remove_cartmodel_cart_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="quantity",
            field=models.FloatField(default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="prd_price",
            field=models.FloatField(max_length=70, null=True),
        ),
    ]
