# Generated by Django 4.2.3 on 2023-08-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0011_rename_prd_name_productmodel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce_app.productmodel",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="name",
            field=models.CharField(max_length=70, null=True),
        ),
    ]
