# Generated by Django 4.2.3 on 2023-08-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0012_ordermodel_product_alter_productmodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartmodel",
            name="product_name",
            field=models.CharField(max_length=70, null=True),
        ),
    ]
