# Generated by Django 4.2.3 on 2023-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0013_cartmodel_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="product_name",
            field=models.CharField(max_length=70, null=True),
        ),
    ]
